#include "main.h"     /* generated by CubeMX - declares hspi2, huart3 */
#include <stdio.h>
#include <string.h>

//#define BMP_CS_GPIO_PORT   GPIOA
//#define BMP_CS_PIN         GPIO_PIN_0

//#define BMP_CS_Pin GPIO_PIN_1
//#define BMP_CS_GPIO_Port GPIOB

#define BMP_CS_LOW()   HAL_GPIO_WritePin(BMP_CS_GPIO_Port, BMP_CS_Pin, GPIO_PIN_RESET)
#define BMP_CS_HIGH()  HAL_GPIO_WritePin(BMP_CS_GPIO_Port, BMP_CS_Pin, GPIO_PIN_SET)


/* ============================================================
 * BMP280 REGISTERS / COMMANDS
 * ============================================================ */

#define BMP280_REG_CHIP_ID     0xD0
#define BMP280_REG_CTRL_MEAS   0xF4
#define BMP280_REG_CONFIG      0xF5
#define BMP280_REG_PRESS_MSB   0xF7
#define BMP280_REG_CALIB_START 0x88

#define BMP280_CHIP_ID_EXPECTED 0x58

/* osrs_t=1, osrs_p=1, mode=normal(11) */
#define BMP280_CTRL_MEAS_NORMAL 0x27

#define SPI_TIMEOUT_MS 100


/* ============================================================
 * LOW-LEVEL SPI VIA HAL
 * ============================================================ */

static uint8_t BMP_ReadReg(uint8_t reg)
{
    uint8_t tx[2] = { (uint8_t)(reg | 0x80), 0x00 };
    uint8_t rx[2] = { 0 };

    BMP_CS_LOW();
    HAL_SPI_TransmitReceive(&hspi2, tx, rx, 2, SPI_TIMEOUT_MS);
    BMP_CS_HIGH();

    return rx[1];
}

static void BMP_ReadRegs(uint8_t start_reg, uint8_t *buffer, uint8_t len)
{
    uint8_t tx = (uint8_t)(start_reg | 0x80);

    BMP_CS_LOW();
    HAL_SPI_Transmit(&hspi2, &tx, 1, SPI_TIMEOUT_MS);
    HAL_SPI_Receive(&hspi2, buffer, len, SPI_TIMEOUT_MS);
    BMP_CS_HIGH();
}

static void BMP_WriteReg(uint8_t reg, uint8_t value)
{
    uint8_t tx[2] = { (uint8_t)(reg & 0x7F), value };

    BMP_CS_LOW();
    HAL_SPI_Transmit(&hspi2, tx, 2, SPI_TIMEOUT_MS);
    BMP_CS_HIGH();
}


/* ============================================================
 * CALIBRATION DATA + COMPENSATION
 * (Bosch's published BMP280 fixed-point reference formulas -
 *  chip-specific, not MCU-specific)
 * ============================================================ */

typedef struct {
    uint16_t dig_T1;
    int16_t  dig_T2, dig_T3;
    uint16_t dig_P1;
    int16_t  dig_P2, dig_P3, dig_P4, dig_P5, dig_P6, dig_P7, dig_P8, dig_P9;
} BMP280_Calib;

static BMP280_Calib calib;
static int32_t t_fine;

static void BMP_ReadCalibration(void)
{
    uint8_t buf[24];

    BMP_ReadRegs(BMP280_REG_CALIB_START, buf, 24);

    calib.dig_T1 = (uint16_t)(buf[0]  | (buf[1]  << 8));
    calib.dig_T2 = (int16_t)(buf[2]  | (buf[3]  << 8));
    calib.dig_T3 = (int16_t)(buf[4]  | (buf[5]  << 8));
    calib.dig_P1 = (uint16_t)(buf[6]  | (buf[7]  << 8));
    calib.dig_P2 = (int16_t)(buf[8]  | (buf[9]  << 8));
    calib.dig_P3 = (int16_t)(buf[10] | (buf[11] << 8));
    calib.dig_P4 = (int16_t)(buf[12] | (buf[13] << 8));
    calib.dig_P5 = (int16_t)(buf[14] | (buf[15] << 8));
    calib.dig_P6 = (int16_t)(buf[16] | (buf[17] << 8));
    calib.dig_P7 = (int16_t)(buf[18] | (buf[19] << 8));
    calib.dig_P8 = (int16_t)(buf[20] | (buf[21] << 8));
    calib.dig_P9 = (int16_t)(buf[22] | (buf[23] << 8));
}

/* Returns temperature in 0.01 degC (e.g. 2354 = 23.54 C) */
static int32_t BMP_CompensateTemp(int32_t adc_T)
{
    int32_t var1, var2;

    var1 = ((((adc_T >> 3) - ((int32_t)calib.dig_T1 << 1))) * ((int32_t)calib.dig_T2)) >> 11;
    var2 = (((((adc_T >> 4) - ((int32_t)calib.dig_T1)) *
              ((adc_T >> 4) - ((int32_t)calib.dig_T1))) >> 12) *
            ((int32_t)calib.dig_T3)) >> 14;

    t_fine = var1 + var2;

    return (t_fine * 5 + 128) >> 8;
}

/* Returns pressure in Pa (must be called after BMP_CompensateTemp) */
static uint32_t BMP_CompensatePressure(int32_t adc_P)
{
    int64_t var1, var2, p;

    var1 = ((int64_t)t_fine) - 128000;
    var2 = var1 * var1 * (int64_t)calib.dig_P6;
    var2 = var2 + ((var1 * (int64_t)calib.dig_P5) << 17);
    var2 = var2 + (((int64_t)calib.dig_P4) << 35);
    var1 = ((var1 * var1 * (int64_t)calib.dig_P3) >> 8) +
           ((var1 * (int64_t)calib.dig_P2) << 12);
    var1 = ((((int64_t)1 << 47) + var1)) * ((int64_t)calib.dig_P1) >> 33;

    if (var1 == 0)
        return 0;

    p = 1048576 - adc_P;
    p = (((p << 31) - var2) * 3125) / var1;
    var1 = (((int64_t)calib.dig_P9) * (p >> 13) * (p >> 13)) >> 25;
    var2 = (((int64_t)calib.dig_P8) * p) >> 19;
    p = ((p + var1 + var2) >> 8) + (((int64_t)calib.dig_P7) << 4);

    return (uint32_t)(p / 256);
}


/* ============================================================
 * LOGGING VIA USART3
 * ============================================================ */

static void Log(const char *str)
{
    HAL_UART_Transmit(&huart3, (uint8_t *)str, (uint16_t)strlen(str), SPI_TIMEOUT_MS);
}


/* ============================================================
 * PUBLIC ENTRY POINT - call this from main() after
 * MX_SPI2_Init() and MX_USART3_UART_Init()
 * ============================================================ */

void BMP280_RunDemo(void)
{
    uint8_t chip_id;
    uint8_t raw[6];
    int32_t adc_T, adc_P, temp_x100;
    uint32_t pressure_pa;
    char line[64];

    BMP_CS_HIGH(); /* deselected at idle */

    Log("\r\nBMP280 over SPI2 / logging over USART3\r\n");

    chip_id = BMP_ReadReg(BMP280_REG_CHIP_ID);
    snprintf(line, sizeof(line), "Chip ID: 0x%02X\r\n", chip_id);
    Log(line);

    if (chip_id != BMP280_CHIP_ID_EXPECTED)
    {
        Log("WARNING: expected 0x58 - check wiring before trusting readings\r\n");
    }

    BMP_ReadCalibration();
    BMP_WriteReg(BMP280_REG_CONFIG, 0x00);
    BMP_WriteReg(BMP280_REG_CTRL_MEAS, BMP280_CTRL_MEAS_NORMAL);

    while (1)
    {
        BMP_ReadRegs(BMP280_REG_PRESS_MSB, raw, 6);

        adc_P = ((int32_t)raw[0] << 12) | ((int32_t)raw[1] << 4) | (raw[2] >> 4);
        adc_T = ((int32_t)raw[3] << 12) | ((int32_t)raw[4] << 4) | (raw[5] >> 4);

        temp_x100  = BMP_CompensateTemp(adc_T);
        pressure_pa = BMP_CompensatePressure(adc_P);

        snprintf(line, sizeof(line), "Temp: %ld.%02ld C  Pressure: %lu.%02lu hPa\r\n",
                 (long)(temp_x100 / 100), (long)(temp_x100 % 100 < 0 ? -(temp_x100 % 100) : temp_x100 % 100),
                 (unsigned long)(pressure_pa / 100), (unsigned long)(pressure_pa % 100));
        Log(line);

        HAL_Delay(1000);
    }
}
